name: Machine Learning CI

on:
 push:
   branches: [ main, master ]
 pull_request:
   branches: [ main, master ]

jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       python-version: ["3.11"]

   steps:
   - uses: actions/checkout@v4
   - name: Set up Python 
     uses: actions/setup-python@v4
     with:
       python-version: ${{ matrix.python-version }}
   - name: Set up environment variables from .env
     run: |
      export $(cat .env | xargs)
   - name: Turn on 'editable' mode
     run: |
          pipenv install -e 
   - name: Install machine learning dependencies and test
     working-directory: machine-learning-client
     run: |
      pipenv install -r requirements.txt
      pipenv install pytest
      pipenv --venv
      pipenv run pytest tests/test_food_detection.py