name: Web App CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint flask  # Install pylint and flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pymongo dotenv

      - name: Run Pytest
        working-directory: ./web-app
        run: |
          pipenv run pytest
